### ISSUE TITLE
Usage without action keyword

### ISSUE THREAD

**Issue by ken0876** [Garulf/Steam-Search#30]
If using the plugin without a keyword, so the default "*" is set, results do not shown up. 
Only if changing priority to 1 or higher, the results appear. - Took me a lot of time to figure this out.

Other FlowLauncher plugins like the Epic Games Launcher work out of the box, if removing the keyword.
Could this be fixed?

**Comment by Garulf** [comment]
Should be relatively simple fix. I'll look into it.

**Comment by Garulf** [comment]
Fixed in: https://github.com/Garulf/Steam-Search/pull/38
