### ISSUE TITLE
Trojan?

### ISSUE THREAD

**Issue by sebastien-k** [Garulf/Steam-Search#50]
Windows Defender says there is a virus when I use your pluguin: 

Trojan:Win32/Wacatac.H!ml

file: C:\Users\XXXXXXX\AppData\Local\Temp\onefile_40668_133257436757793870\run.exe
file: C:\Users\XXXXXXX\AppData\Local\Temp\onefile_47128_133257436759934243\run.exe
file: C:\Users\XXXXXXX\AppData\Local\Temp\onefile_53844_133257436756088574\run.exe

**Comment by Garulf** [comment]
@sebastien-k Version 9.0.0 changed the way the plugin is packaged and should not be flagged as a false positive. Please let me know if you still have issues.
