### ISSUE TITLE
Steam library not found

### ISSUE THREAD

**Issue by FilipNone** [Garulf/Steam-Search#52]
For some reason I can't setup "correctly" the steam library.
![immagine](https://user-images.githubusercontent.com/79002362/232542082-859de42e-f46e-44a0-ad52-d829a699f230.png)

The directory on the plugin seems correct:
![immagine](https://user-images.githubusercontent.com/79002362/232542536-89453a7e-68d2-4173-8080-a679fda3fbfa.png)

So I don't understand why...

**Comment by Garulf** [comment]
That settings is looking for the directory that contains your `steam.exe` not the executable itself. Please change the "Steam Executable Directory" setting to: `C:\Program Files (x86)\Steam` or simple leave it blank as the plugin *should* auto insert this path as 99% of installs are to this path.

### Please make sure to close the settings window to save and apply the new settings.

![image](https://user-images.githubusercontent.com/535299/232882010-41e860bd-ccb2-4b68-8903-2abeb3bf41fb.png)

**Comment by FilipNone** [comment]
I did as you say but now the situation is worse...
![immagine](https://user-images.githubusercontent.com/79002362/233385920-70d9d898-4010-4caa-94ab-b5aeada285f5.png)

**Comment by Garulf** [comment]
The grid issue is fixed in version 9.0.1. Please update your plugin. 

Either way I'm glad it's working for you.
