### ISSUE TITLE
doesnt work at all

### ISSUE THREAD

**Issue by shalolaauthor** [Garulf/Steam-Search#58]
st dota2 doesnt show up. st doesnt show all games i own. enabled. 

![image](https://github.com/Garulf/Steam-Search/assets/124796924/a42e77fe-d161-490b-ace2-530ba976c887)
![image](https://github.com/Garulf/Steam-Search/assets/124796924/6565364e-f419-4c53-a49a-8183684538bb)

**Comment by shalolaauthor** [comment]
![image](https://github.com/Garulf/Steam-Search/assets/124796924/0a62f970-fa4a-4a0f-9023-b57144c4300f)

**Comment by Garulf** [comment]
Ah that's not Flow Launcher. That's Microsoft Powertoys Run.

**Comment by Garulf** [comment]
Closing due to non-issue. 

If you’re still having trouble please reopen.
