### ISSUE TITLE
when i type “st” to use ，it must be lowercase,if it's "ST" will no effect

### ISSUE THREAD

**Issue by Yia-wooh** [Garulf/Steam-Search#65]

**Comment by indigofairyx** [comment]
I've noticed this is universal oddity wit case sensitive throughout flow launcher. Eg  the built in url command won't work if it's URL

**Comment by Garulf** [comment]
Thank you for reporting this issue, unfortunately plugins have little control over this. 

Please report this issue with Flow Launcher.
